# Generated by Django 2.2.3 on 2020-08-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurveyMeterName', models.CharField(max_length=30, null=True)),
                ('MeterSN', models.CharField(max_length=30, null=True)),
                ('CalibrationLab', models.CharField(max_length=30, null=True)),
                ('CalibraionDate', models.DateTimeField(null=True)),
                ('CalibraionDue', models.DateTimeField(null=True)),
                ('CalCerfiticate', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
