# Generated by Django 2.2.3 on 2020-08-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquipmentCalibrations', '0002_auto_20200809_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellChamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('SN', models.CharField(max_length=30, null=True)),
                ('CalibrationLab', models.CharField(max_length=30, null=True)),
                ('CalibrationFactor', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('CalibrationDate', models.DateTimeField(null=True)),
                ('CalibrationDue', models.DateTimeField(null=True)),
                ('CalCerfiticate', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
