# Generated by Django 2.2.3 on 2020-06-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelIDNumber', models.IntegerField(default=0)),
                ('ChannelMapNumber', models.IntegerField(default=0)),
                ('StepSize', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ChannelLength', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ChannelTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('NumberOfControlPoints', models.IntegerField(default=0)),
                ('FinalTimeWeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckSetValuesCylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelLengthVal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('StepSizeVal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MapNumVal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CheckSetValuesTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelLengthVal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('StepSizeVal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CylinderCheckActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelLength', models.BooleanField(default=True)),
                ('ChannelMapNum', models.BooleanField(default=True)),
                ('StepSize', models.BooleanField(default=True)),
                ('RxDist', models.BooleanField(default=True)),
                ('RxDose', models.BooleanField(default=True)),
                ('PlanNormalization', models.BooleanField(default=True)),
                ('PlanOptimization', models.BooleanField(default=True)),
                ('CheckTxUnit', models.BooleanField(default=True)),
                ('ChannelNum', models.BooleanField(default=True)),
                ('CheckDosePointDistance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HDRCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(default='HDR', max_length=30)),
                ('PatientName', models.CharField(default='HDR', max_length=30)),
                ('NumFractions', models.IntegerField(default=0)),
                ('CourseType', models.CharField(default='HDR', max_length=30)),
                ('TxType', models.CharField(default='Cyl', max_length=30)),
                ('RXDose', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('RXDist', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('PatientName', 'CourseName')},
            },
        ),
        migrations.CreateModel(
            name='HDRFraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanFile', models.FileField(null=True, upload_to='')),
                ('FxNum', models.IntegerField(default=0)),
                ('Acivity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Dose', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('TxTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Date', models.DateField(null=True)),
                ('HDRCourse', models.ForeignKey(default='HDR', on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRCourse')),
            ],
        ),
        migrations.CreateModel(
            name='HDRPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(blank=True, max_length=100)),
                ('TxType', models.CharField(max_length=20, null=True)),
                ('PatientName', models.CharField(max_length=30, null=True)),
                ('PlanName', models.CharField(default='HDR', max_length=30)),
                ('LoaderName', models.CharField(blank=True, max_length=30)),
                ('Isotope', models.CharField(blank=True, max_length=30)),
                ('Rx_dose', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Kerma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PlanActivity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('CurrActivity', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('RefDate', models.DateTimeField(null=True)),
                ('Time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dicomFile', models.FileField(upload_to='')),
                ('StepSize', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('NumFx', models.IntegerField(null=True)),
                ('PlanOptimization', models.CharField(blank=True, max_length=30)),
                ('PlanNormalization', models.CharField(blank=True, max_length=30)),
                ('Course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRCourse')),
                ('Fraction', models.ManyToManyField(to='HDRPlanCheck.HDRFraction')),
            ],
            options={
                'unique_together': {('Course', 'PlanName')},
            },
        ),
        migrations.CreateModel(
            name='tempPlanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TempFile', models.FileField(default='no File', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TOCheckActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelLength', models.BooleanField(default=True)),
                ('StepSize', models.BooleanField(default=True)),
                ('RxDose', models.BooleanField(default=True)),
                ('PlanNormalization', models.BooleanField(default=True)),
                ('PlanOptimization', models.BooleanField(default=True)),
                ('CheckTxUnit', models.BooleanField(default=True)),
                ('ChannelNum', models.BooleanField(default=True)),
                ('CheckDosePointDistance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceControlPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPointXpos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CPointYpos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CPointZpos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ControlPtIndex', models.IntegerField(default=0)),
                ('RelativePosition', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('PreviousCumTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CummulativeTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('TimeAtPosition', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FinalTimeWeight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Channel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='HDRTxCheckSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FxNum', models.IntegerField(default=0)),
                ('CheckType', models.CharField(blank=True, max_length=30)),
                ('Acivity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Dose', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('TxTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('HDRFraction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRFraction')),
            ],
        ),
        migrations.CreateModel(
            name='HDRPlanCheckSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckType', models.CharField(blank=True, max_length=30)),
                ('Plan', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRPlan')),
            ],
        ),
        migrations.CreateModel(
            name='HDRPlanCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('PlanType', models.CharField(blank=True, max_length=30)),
                ('CheckDescription', models.CharField(blank=True, max_length=120)),
                ('Result', models.CharField(blank=True, max_length=30)),
                ('Value', models.CharField(blank=True, max_length=30)),
                ('ExpectedValue', models.CharField(blank=True, max_length=30)),
                ('PlanNormalization', models.BooleanField(default=True)),
                ('PlanCheckSet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRPlanCheckSet')),
            ],
        ),
        migrations.AddField(
            model_name='hdrfraction',
            name='HDRPlan',
            field=models.ManyToManyField(default=1, to='HDRPlanCheck.HDRPlan'),
        ),
        migrations.CreateModel(
            name='DosePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DosePointX', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('DosePointY', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('DosePointZ', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Dose', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('RefNumber', models.CharField(blank=True, max_length=5)),
                ('HDRPlan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRPlan')),
            ],
        ),
        migrations.CreateModel(
            name='dicomFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicomFile', models.FileField(upload_to='')),
                ('PlanName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRPlan')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='Plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HDRPlanCheck.HDRPlan'),
        ),
    ]
