# Generated by Django 2.2.3 on 2020-06-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('HDRPlanCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdrcourse',
            name='Patient',
            field=models.ForeignKey(default='John', on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient'),
        ),
    ]
