# Generated by Django 2.2.3 on 2020-11-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SourceExchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KermaMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Pressure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ElectormeterCal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('WellCal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SweetMeaure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SourceExchangeQA', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SourceExchange.SourceExchangeQA')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Measurement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Position', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('KermaMeasure', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SourceExchange.KermaMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Measurement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='timerlinearity',
            old_name='Seconds15',
            new_name='Linearity',
        ),
        migrations.RemoveField(
            model_name='timerlinearity',
            name='Seconds30',
        ),
        migrations.RemoveField(
            model_name='timerlinearity',
            name='Seconds45',
        ),
        migrations.RemoveField(
            model_name='timerlinearity',
            name='Seconds60',
        ),
        migrations.DeleteModel(
            name='SweetSpotMeasure',
        ),
        migrations.AddField(
            model_name='timemeasure',
            name='SourceExchangeQA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SourceExchange.TimerLinearity'),
        ),
    ]
