# Generated by Django 2.2.3 on 2020-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QATestDate', models.DateTimeField(null=True)),
                ('DoorTest', models.BooleanField(default=True)),
                ('EmergencyStopTest', models.BooleanField(default=True)),
                ('StartUpTest', models.BooleanField(default=True)),
                ('PauseTest', models.BooleanField(default=True)),
                ('Completed', models.BooleanField(default=True)),
                ('SourceActivity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('CalculatedActivity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('StopWatchTimer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SourcePositionMeasured', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SourcePositionProgramed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('SurveyMeter', models.CharField(max_length=30, null=True)),
                ('SurveyMCalibrationDue', models.DateTimeField(null=True)),
            ],
        ),
    ]
