# Generated by Django 2.2.3 on 2020-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyQA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyqa',
            name='CalculatedActivity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqa',
            name='SourceActivity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqa',
            name='SourcePositionMeasured',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqa',
            name='SourcePositionProgramed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqa',
            name='StopWatchTimer',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
