# Generated by Django 2.2.3 on 2020-08-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyQA', '0003_auto_20200719_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyqa',
            name='QATestDate',
            field=models.DateTimeField(null=True),
        ),
    ]
