# Generated by Django 2.2.5 on 2020-01-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMRrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requestor', models.CharField(max_length=25)),
                ('EMRSystem', models.CharField(max_length=25)),
                ('Request', models.CharField(max_length=300)),
                ('Reason', models.CharField(max_length=300)),
                ('Priority', models.CharField(max_length=20)),
                ('Impact', models.CharField(max_length=300)),
                ('Comment', models.CharField(max_length=300)),
            ],
        ),
    ]
