# Generated by Django 2.2.5 on 2020-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrrequest',
            name='Comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='EMRSystem',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Impact',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Priority',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Reason',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Request',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Requestor',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
