# Generated by Django 2.2.5 on 2020-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0002_auto_20200128_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='emrrequest',
            name='Status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='emrrequest',
            name='TimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
