# Generated by Django 2.2.5 on 2020-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0004_auto_20200128_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='emrrequest',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
