# Generated by Django 2.2.5 on 2020-01-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0006_auto_20200130_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrrequest',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
