# Generated by Django 2.2.5 on 2020-02-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0007_auto_20200130_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrrequest',
            name='Impact',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Priority',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Reason',
            field=models.CharField(default='', max_length=300),
        ),
    ]
