# Generated by Django 2.2.5 on 2020-02-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0008_auto_20200210_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='emrrequest',
            name='ActionTaken',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='emrrequest',
            name='Phone',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='emrrequest',
            name='TeamMember',
            field=models.CharField(default='', max_length=30),
        ),
    ]
