# Generated by Django 2.2.5 on 2020-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0009_auto_20200219_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='emrrequest',
            name='DateCompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
