# Generated by Django 2.2.5 on 2020-02-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0010_emrrequest_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrrequest',
            name='DateCompleted',
            field=models.DateTimeField(default=''),
        ),
    ]
