# Generated by Django 2.2.5 on 2020-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0012_auto_20200220_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrrequest',
            name='ActionTaken',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Comment',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Impact',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Reason',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='emrrequest',
            name='Request',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
