# Generated by Django 2.2.5 on 2020-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMRrequest', '0013_auto_20200313_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emrrequest',
            name='Impact',
            field=models.CharField(default='', max_length=400),
        ),
    ]
